services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  shell:
    image: libqless/dev-shell
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    working_dir: /app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: ["bash"]
    stdin_open: true
    tty: true

volumes:
  bundle:
