#! /usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
require 'optparse'
require 'rack'
require 'thin'
require 'qless/server'

options = {
  host: ENV['HOST'] || '0.0.0.0',
  port: (ENV['PORT'] || 9292).to_i
}

OptionParser.new do |opts|
  opts.banner = 'Usage: qless-web [options]'
  opts.on('-o', '--host HOST', 'Host to bind (default: 0.0.0.0)') { |h| options[:host] = h }
  opts.on('-p', '--port PORT', Integer, 'Port to listen on (default: 9292)') { |p| options[:port] = p }
end.parse!

client = Qless::Client.new
app = Qless::Server.new(client)

Rack::Handler::Thin.run(app, Host: options[:host], Port: options[:port])
