name: Tests

on:
  push:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "ruby ${{ matrix.ruby-version }} | redis ${{ matrix.redis-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        redis-version:
          - "redis:7"
          - "redis:8"
          - "valkey/valkey:7.2"
          - "valkey/valkey:8.0"
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - "head"

    services:
      redis:
        image: ${{ matrix.redis-version }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
        timeout-minutes: 10
